### ISSUE TITLE
Project not runnable

### ISSUE THREAD

**Issue by kuro7766** [hanxjing/AKD-DBPR#2]
File open error : cloth.binary.p
I download it from [here ](https://drive.google.com/drive/folders/1g3MVuKsnAL-7-QByDyb_kWXHgVjzFP5z)
```
extract rule done!
writing...
writing done!
loading w2v data... Traceback (most recent call last):
  File "matching_attention.py", line 727, in <module>
    train()
  File "matching_attention.py", line 38, in train
    x = pickle.load(open("./cloth.binary.p", "rb"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 33: ordinal not in range(128)
```

And how to get these three `*_text.pkl` files?
```
train_i, train_j, train_k = pickle.load(open("./data_mm_text/AUC_new_dataset_train_811_text.pkl", "rb"))
valid_i, valid_j, valid_k = pickle.load(open("./data_mm_text/AUC_new_dataset_valid_811_text.pkl", "rb"))
test_i, test_j, test_k = pickle.load(open("./data_mm_text/AUC_new_dataset_test_811_text.pkl", "rb"))
```

**Comment by hanxjing** [comment]
> File open error : cloth.binary.p
> I download it from [here ](https://drive.google.com/drive/folders/1g3MVuKsnAL-7-QByDyb_kWXHgVjzFP5z)
> 
> ```
> extract rule done!
> writing...
> writing done!
> loading w2v data... Traceback (most recent call last):
>   File "matching_attention.py", line 727, in <module>
>     train()
>   File "matching_attention.py", line 38, in train
>     x = pickle.load(open("./cloth.binary.p", "rb"))
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xa8 in position 33: ordinal not in range(128)
> ```
> 
> And how to get these three `*_text.pkl` files?
> 
> ```
> train_i, train_j, train_k = pickle.load(open("./data_mm_text/AUC_new_dataset_train_811_text.pkl", "rb"))
> valid_i, valid_j, valid_k = pickle.load(open("./data_mm_text/AUC_new_dataset_valid_811_text.pkl", "rb"))
> test_i, test_j, test_k = pickle.load(open("./data_mm_text/AUC_new_dataset_test_811_text.pkl", "rb"))
> ```

Thanks for your attention. 
-Try `sys.setdefaultencoding('utf-8')` for the UnicodeDecodeError.
-All the experimental data can be downloaded from the provided link. `*_text.pkl` files are provided in text_data.rar with different file names.

**Comment by kuro7766** [comment]
An unknown import error 
```
Traceback (most recent call last):
  File "E:/code/pythonproject/AKB/AKD-DBPR-master/model/matching_attention.py", line 762, in <module>
    train()
  File "E:/code/pythonproject/AKB/AKD-DBPR-master/model/matching_attention.py", line 306, in train
    set_zero = theano.function([zero_vec_tensor],
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\compile\function.py", line 306, in function
    fn = pfunc(params=inputs,
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\compile\pfunc.py", line 483, in pfunc
    return orig_function(inputs, cloned_outputs, mode,
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\compile\function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\compile\function_module.py", line 1714, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\link.py", line 697, in make_thunk
    return self.make_all(input_storage=input_storage,
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\vm.py", line 1087, in make_all
    thunks.append(node.op.make_thunk(node,
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\op.py", line 954, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map,
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\op.py", line 857, in make_c_thunk
    outputs = cl.make_thunk(input_storage=node_input_storage,
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py", line 1215, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py", line 1153, in __compile__
    thunk, module = self.cthunk_factory(error_storage,
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py", line 1623, in cthunk_factory
    module = get_module_cache().module_from_key(
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cmodule.py", line 1189, in module_from_key
    module = lnk.compile_cmodule(location)
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cc.py", line 1520, in compile_cmodule
    module = c_compiler.compile_str(
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cmodule.py", line 2420, in compile_str
    return dlimport(lib_filename)
  File "C:\Users\1\AppData\Local\Programs\Python\Python38\lib\site-packages\theano\gof\cmodule.py", line 317, in dlimport
    rval = __import__(module_name, {}, {}, [module_name])
ImportError: DLL load failed while importing m00ab969b216509af6f377c2463818944030bff45313c5cca8b5089834b94942e: 找不到指定的模块。
```
At ```  File "E:/code/pythonproject/AKB/AKD-DBPR-master/model/matching_attention.py", line 306, in train```


this line :
```
                set_zero = theano.function([zero_vec_tensor],
                                           updates=[(Words, T.set_subtensor(Words[0, :], zero_vec_tensor))],
                                           allow_input_downcast=True)
```
